# @StudioIA.Api_HostAddress = http://localhost:5098
@StudioIA.Api_HostAddress = http://localhost:5202

GET {{StudioIA.Api_HostAddress}}/api/health
Accept: application/json

###

POST {{StudioIA.Api_HostAddress}}/api/auth/sign-in
Content-Type: application/json

{
  "email": "admin@studioia.com",
  "password": "123Qwe"
}

###

GET {{StudioIA.Api_HostAddress}}/api/admin/catalog/categories
Accept: application/json

###

GET {{StudioIA.Api_HostAddress}}/api/admin/catalog/agents
Accept: application/json

###

GET {{StudioIA.Api_HostAddress}}/api/client-accounts
Accept: application/json

###

GET {{StudioIA.Api_HostAddress}}/swagger/v1/swagger.json
Accept: application/json
